### ISSUE TITLE
libcudart.so not found on system with multiple CUDA versions

### ISSUE THREAD

**Issue by garymm** [bazel-contrib/rules_cuda#113] opened 2023-06-28 18:29 UTC
On a system with two versions of CUDA installed like so:
```
➜  ls -ld /usr/local/cuda*
lrwxrwxrwx  1 root   20 Jun 23 14:05 /usr/local/cuda -> /usr/local/cuda-11.8/
drwxr-xr-x 16 root 4096 Jun 23 13:54 /usr/local/cuda-11.8/
lrwxrwxrwx  1 root   25 Jun  9 18:58 /usr/local/cuda-12 -> /etc/alternatives/cuda-12/
drwxr-xr-x 15 root 4096 Jun 23 14:04 /usr/local/cuda-12.1/
```
And the following WORKSPACE.bazel code:

```bzl
load("@rules_cuda//cuda:repositories.bzl", "local_cuda", "register_detected_cuda_toolchains")

local_cuda(
    name = "local_cuda",
    toolkit_path = "/usr/local/cuda-12.1",
)

register_detected_cuda_toolchains()
```

Binaries seem to get linked against the wrong libcuda.so:
```
➜  ldd bazel-bin/foo | grep libcuda
	libcudart.so.12 => not found
```

On a system that only has one version of CUDA installed, with the same workspace snippet, it seems like libcudart.so is pointing to `/usr/local/cuda`, NOT the `/usr/local/cuda-12.1` specified in the WORKSPACE.

```
➜  ldd bazel-bin/foo | grep libcuda
	libcudart.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12 (0x00007f2cdad20000)
```

Seems the linker is somehow being told to look at `/usr/local/cuda` regardless of the toolkit_path specified.

**Comment by cloudhan** [comment] 2023-06-29 08:47
It is because `cc_import`
https://github.com/bazel-contrib/rules_cuda/blob/18eba6d463db35253788a94fdaa45e9863ab19f0/cuda/runtime/BUILD.local_cuda#L42-L46
cause it linking with **rpath** ([by (my) design](https://github.com/bazel-contrib/rules_cuda/commit/7c88d0a994bef366a5c27bc7b717b060f5b7ba13)).

The problem is multi-fold here.

1. First, I'd assume that you are facing this problem because you are not run it with `bazel run` or `bazel test`.
2. Second question is, what is the rpath here? `patchelf --print-rpath bazel-bin/cublas/main` shows it is (manually splited due to long line) 
    ```
    $ORIGIN/../_solib_k8/_U@local_Ucuda_S_S_CcublasLt_Uso___Ucuda_Slib64
    $ORIGIN/main.runfiles/rules_cuda_examples/_solib_k8/_U@local_Ucuda_S_S_CcublasLt_Uso___Ucuda_Slib64
    $ORIGIN/../_solib_k8/_U@local_Ucuda_S_S_Ccublas_Uso___Ucuda_Slib64
    $ORIGIN/main.runfiles/rules_cuda_examples/_solib_k8/_U@local_Ucuda_S_S_Ccublas_Uso___Ucuda_Slib64`
    ```
3. Third question is, how is the dynamic linker handling the library search
    Previous rpaths means the so files (linked with rpath) like cudart and cublas will only be resolved with these paths before falling back to system-wise configured dl path (`/etc/ld.so.conf`). And for the bazel-bin dir:
    ```
    > tree  bazel-bin/_solib_k8
    bazel-bin/_solib_k8
    ├── _U@local_Ucuda_S_S_CcublasLt_Uso___Ucuda_Slib64
    │   └── libcublasLt.so -> /home/cloud/.cache/bazel/_bazel_cloud/577e4aa5abb1bc82ad9cac7a5312184c/external/local_cuda/cuda/lib64/libcublasLt.so
    ├── _U@local_Ucuda_S_S_Ccublas_Uso___Ucuda_Slib64
    │   └── libcublas.so -> /home/cloud/.cache/bazel/_bazel_cloud/577e4aa5abb1bc82ad9cac7a5312184c/external/local_cuda/cuda/lib64/libcublas.so
    └── _U@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64
        └── libcudart.so -> /home/cloud/.cache/bazel/_bazel_cloud/577e4aa5abb1bc82ad9cac7a5312184c/external/local_cuda/cuda/lib64/libcudart.so
    ```

If you have moved your artifacts out of the `bazel-bin/` or messed with it so the rpath does not actually exist. Then you will fallback to system search path. And if it is found, that one will be loaded. This is also why there will be no problem if you run it with `bazel run` or `bazel test`, the folder content (rpath) will be made correct for you by bazel.

See https://www.eyrie.org/~eagle/notes/rpath.html

**Comment by garymm** [comment] 2023-06-29 17:13
Thanks for taking a look!

1. Incorrect, It fails with `bazel test`.
2. patchelf --print-rpath output:
```
$ORIGIN/../../_solib_x86-64/
$ORIGIN/inhib_test.runfiles/__main__/_solib_x86-64/
$ORIGIN/../../_solib_x86-64/_U@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64
$ORIGIN/inhib_test.runfiles/__main__/_solib_x86-64/_U@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64
/home/garymm/.cache/bazel/_bazel_garymm/ccc6d0766f673e3e9724a5903508d1e5/external/gcc_toolchain_files/x86_64-buildroot-linux-gnu/sysroot/lib
/home/garymm/.cache/bazel/_bazel_garymm/ccc6d0766f673e3e9724a5903508d1e5/external/gcc_toolchain_files/x86_64-buildroot-linux-gnu/sysroot/usr/lib
/home/garymm/.cache/bazel/_bazel_garymm/ccc6d0766f673e3e9724a5903508d1e5/external/gcc_toolchain_files/x86_64-buildroot-linux-gnu/sysroot/../lib64
```

Maybe it's a clue that `ldd` shows the binary is linked against `libcudart.so.12`, but the rpath directory only contains `libcudart.so`.

**Closed** 2023-07-06 10:58 UTC
